name: dependency-updates
on:
  push:
    branches:
      - latest
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  aws-lc-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update aws-lc version
        id: update
        run: |
          AWSLC_VERSION="$(
          git ls-remote --tags --refs https://github.com/aws/aws-lc \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          AWSLC_SHA="$(git ls-remote https://github.com/aws/aws-lc "$AWSLC_VERSION" | cut -f1)"
          sed -i "s|ARG AWSLC_VERSION=.*|ARG AWSLC_VERSION=$AWSLC_SHA # $AWSLC_VERSION|" Dockerfile
          echo "version=$AWSLC_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update aws-lc version to ${{ steps.update.outputs.version }}
          branch: update-aws-lc-version
          title: update aws-lc version to ${{ steps.update.outputs.version }}
          body: update aws-lc version to ${{ steps.update.outputs.version }}
  ngtcp2-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update ngtcp2 version
        id: update
        run: |
          NGTCP2_VERSION="$(
          git ls-remote --tags --refs https://github.com/ngtcp2/ngtcp2 \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          NGTCP2_SHA="$(git ls-remote https://github.com/ngtcp2/ngtcp2 "$NGTCP2_VERSION" | cut -f1)"
          sed -i "s|ARG NGTCP2_VERSION=.*|ARG NGTCP2_VERSION=$NGTCP2_SHA # $NGTCP2_VERSION|" Dockerfile
          echo "version=$NGTCP2_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update ngtcp2 version to ${{ steps.update.outputs.version }}
          branch: update-ngtcp2-version
          title: update ngtcp2 version to ${{ steps.update.outputs.version }}
          body: update ngtcp2 version to ${{ steps.update.outputs.version }}
  nghttp3-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update nghttp3 version
        id: update
        run: |
          NGHTTP3_VERSION="$(
          git ls-remote --tags --refs https://github.com/ngtcp2/nghttp3 \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          NGHTTP3_SHA="$(git ls-remote https://github.com/ngtcp2/nghttp3 "$NGHTTP3_VERSION" | cut -f1)"
          sed -i "s|ARG NGHTTP3_VERSION=.*|ARG NGHTTP3_VERSION=$NGHTTP3_SHA # $NGHTTP3_VERSION|" Dockerfile
          echo "version=$NGHTTP3_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update nghttp3 version to ${{ steps.update.outputs.version }}
          branch: update-nghttp3-version
          title: update nghttp3 version to ${{ steps.update.outputs.version }}
          body: update nghttp3 version to ${{ steps.update.outputs.version }}
  nghttp2-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update nghttp2 version
        id: update
        run: |
          NGHTTP2_VERSION="$(
          git ls-remote --tags --refs https://github.com/nghttp2/nghttp2 \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          NGHTTP2_SHA="$(git ls-remote https://github.com/nghttp2/nghttp2 "$NGHTTP2_VERSION" | cut -f1)"
          sed -i "s|ARG NGHTTP2_VERSION=.*|ARG NGHTTP2_VERSION=$NGHTTP2_SHA # $NGHTTP2_VERSION|" Dockerfile
          echo "version=$NGHTTP2_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update nghttp2 version to ${{ steps.update.outputs.version }}
          branch: update-nghttp2-version
          title: update nghttp2 version to ${{ steps.update.outputs.version }}
          body: update nghttp2 version to ${{ steps.update.outputs.version }}
  zstd-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update zstd version
        id: update
        run: |
          ZSTD_VERSION="$(
          git ls-remote --tags --refs https://github.com/facebook/zstd \
              | cut -d/ -f3 \
              | grep "^v\?[0-9.]\+$" \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          ZSTD_SHA="$(git ls-remote https://github.com/facebook/zstd "$ZSTD_VERSION" | cut -f1)"
          sed -i "s|ARG ZSTD_VERSION=.*|ARG ZSTD_VERSION=$ZSTD_SHA # $ZSTD_VERSION|" Dockerfile
          echo "version=$ZSTD_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update zstd version to ${{ steps.update.outputs.version }}
          branch: update-zstd-version
          title: update zstd version to ${{ steps.update.outputs.version }}
          body: update zstd version to ${{ steps.update.outputs.version }}
  brotli-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update brotli version
        id: update
        run: |
          BROTLI_VERSION="$(
          git ls-remote --tags --refs https://github.com/google/brotli \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          BROTLI_SHA="$(git ls-remote https://github.com/google/brotli "$BROTLI_VERSION" | cut -f1)"
          sed -i "s|ARG BROTLI_VERSION=.*|ARG BROTLI_VERSION=$BROTLI_SHA # $BROTLI_VERSION|" Dockerfile
          echo "version=$BROTLI_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update brotli version to ${{ steps.update.outputs.version }}
          branch: update-brotli-version
          title: update brotli version to ${{ steps.update.outputs.version }}
          body: update brotli version to ${{ steps.update.outputs.version }}
  zlibng-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update zlibng version
        id: update
        run: |
          ZLIBNG_VERSION="$(
          git ls-remote --tags --refs https://github.com/zlib-ng/zlib-ng \
              | cut -d/ -f3 \
              | grep "^[0-9.]\+$" \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          ZLIBNG_SHA="$(git ls-remote https://github.com/zlib-ng/zlib-ng "$ZLIBNG_VERSION" | cut -f1)"
          sed -i "s|ARG ZLIBNG_VERSION=.*|ARG ZLIBNG_VERSION=$ZLIBNG_SHA # $ZLIBNG_VERSION|" Dockerfile
          echo "version=$ZLIBNG_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update zlibng version to ${{ steps.update.outputs.version }}
          branch: update-zlibng-version
          title: update zlibng version to ${{ steps.update.outputs.version }}
          body: update zlibng version to ${{ steps.update.outputs.version }}
  curl-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update curl version
        id: update
        run: |
          CURL_VERSION="$(
          git ls-remote --tags --refs https://github.com/curl/curl curl-* \
              | cut -d/ -f3 \
              | sort -V \
              | grep -vi rc \
              | tail -1
          )"
          CURL_SHA="$(git ls-remote https://github.com/curl/curl "$CURL_VERSION" | cut -f1)"
          sed -i "s|ARG CURL_VERSION=.*|ARG CURL_VERSION=$CURL_SHA # $CURL_VERSION|" Dockerfile
          echo "version=$CURL_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: update curl version to ${{ steps.update.outputs.version }}
          branch: update-curl-version
          title: update curl version to ${{ steps.update.outputs.version }}
          body: update curl version to ${{ steps.update.outputs.version }}
