name: Build Docker Image
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: ghcr.io-login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        if: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
          tags: ghcr.io/zoeyvid/curl-quic:latest-x86_64
          build-args: |
            FLAGS=-march=x86-64-v2 -mtune=generic -fcf-protection=full
          
  build-aarch64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: ghcr.io-login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        if: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
          tags: ghcr.io/zoeyvid/curl-quic:latest-aarch64
          build-args: |
            FLAGS=-mbranch-protection=standard
          
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs: [build-x86_64, build-aarch64]
    if: ${{ github.repository_owner == 'ZoeyVid' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: version
        id: version
        run: |
          echo "version=$(sed -n "s|^ARG CURL_VERSION=.* # ||p" Dockerfile | tr "_" ".")-awslc-$(sed -n "s|^ARG AWSLC_VERSION=.* # v||p" Dockerfile)-ngtcp2-$(sed -n "s|^ARG NGTCP2_VERSION=.* # v||p" Dockerfile)-nghttp3-$(sed -n "s|^ARG NGHTTP3_VERSION=.* # v||p" Dockerfile)-nghttp2-$(sed -n "s|^ARG NGHTTP2_VERSION=.* # v||p" Dockerfile)-zstd-$(sed -n "s|^ARG ZSTD_VERSION=.* # v||p" Dockerfile)-brotli-$(sed -n "s|^ARG BROTLI_VERSION=.* # v||p" Dockerfile)-zlibng-$(sed -n "s|^ARG ZLIBNG_VERSION=.* # ||p" Dockerfile)-cares-$(sed -n "s|^ARG CARES_VERSION=.* # v||p" Dockerfile)" >> $GITHUB_OUTPUT
      - name: docker.io-login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: ghcr.io-login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - name: merge
        run: |
          docker buildx imagetools create --tag zoeyvid/curl-quic:latest ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag zoeyvid/curl-quic:${{ github.run_number }} ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag ghcr.io/zoeyvid/curl-quic:latest ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag ghcr.io/zoeyvid/curl-quic:${{ github.run_number }} ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
      - name: extract
        run: |
          docker run -d --pull always --platform amd64 --name curl-x86_64 ghcr.io/zoeyvid/curl-quic:latest-x86_64
          docker cp curl-x86_64:/usr/local/bin/curl curl-x86_64
          docker run -d --pull always --platform arm64 --name curl-aarch64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker cp curl-aarch64:/usr/local/bin/curl curl-aarch64
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: curl-x86_64
          if-no-files-found: error
          retention-days: 3
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          archive: false
          path: curl-aarch64
          if-no-files-found: error
          retention-days: 3
      - name: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete "${{ steps.version.outputs.version }}" --yes --cleanup-tag || true
          gh release create "${{ steps.version.outputs.version }}" curl-x86_64 curl-aarch64 --target "$GITHUB_SHA" --title "${{ steps.version.outputs.version }}" --generate-notes
