name: Build Docker Image
on:
  push:
    branches:
      - latest
  workflow_dispatch:
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ZoeyVid' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/zoeyvid/curl-quic:latest-x86_64
          build-args: |
            FLAGS=-march=x86-64-v2 -mtune=generic -fcf-protection=full
          
  build-aarch64:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.repository_owner == 'ZoeyVid' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/zoeyvid/curl-quic:latest-aarch64
          build-args: |
            FLAGS=-mbranch-protection=standard
          
  merge:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    if: ${{ github.repository_owner == 'ZoeyVid' }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Read version
        id: version
        run: echo "version=$(echo $(cat Dockerfile | grep "^ARG CURL_VERSION=.*$" | sed "s|ARG CURL_VERSION=||g" | sed "s|_|\.|g")-wolfssl-$(cat Dockerfile | grep "^ARG WS_VERSION=.*$" | sed "s|ARG WS_VERSION=v\([0-9.]\+\).*|\1|g")-nghttp3-$(cat Dockerfile | grep "^ARG NGH3_VERSION=.*$" | sed "s|ARG NGH3_VERSION=v||g")-ngtcp2-$(cat Dockerfile | grep "^ARG NGTCP2_VERSION=.*$" | sed "s|ARG NGTCP2_VERSION=v||g"))" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: zoeyvid
          password: ${{ github.token }}
      - name: create multiarch
        run: |
          docker buildx imagetools create --tag zoeyvid/curl-quic:latest ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag zoeyvid/curl-quic:${{ github.run_number }} ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag ghcr.io/zoeyvid/curl-quic:latest ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
          docker buildx imagetools create --tag ghcr.io/zoeyvid/curl-quic:${{ github.run_number }} ghcr.io/zoeyvid/curl-quic:latest-x86_64 ghcr.io/zoeyvid/curl-quic:latest-aarch64
      - name: copy curl binary
        run: |
          docker run -d --pull always --platform amd64 --name curl-x86_64 ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.ref_name }}-x86_64
          docker cp curl-x86_64:/usr/local/bin/curl curl-x86_64
          docker run -d --pull always --platform arm64 --name curl-aarch64 ${{ steps.un.outputs.un }}/${{ github.event.repository.name }}:${{ github.ref_name }}-aarch64
          docker cp curl-aarch64:/usr/local/bin/curl curl-aarch64
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: artifacts
          path: |
            curl-x86_64
            curl-aarch64
      - uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          title: ${{ steps.version.outputs.version }}
          automatic_release_tag: ${{ steps.version.outputs.version }}
          files: |
            curl-x86_64
            curl-aarch64
