name: Dockerlint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-lint:
    runs-on: ubuntu-slim
    name: docker-lint
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: hadolint
        run: |
          set -x
          curl -sSfL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-$(uname -m) -o hadolint
          chmod +x hadolint
          for file in $(find -name "*Dockerfile"); do
            # DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
            # DL3003 warning: Use WORKDIR to switch to a directory
            ./hadolint "$file" --ignore DL3018 --ignore DL3003 | tee -a hadolint.log
          done
          if [ -n "$(cat hadolint.log)" ]; then
            exit 1
          fi
